// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package postgres

import (
	"github.com/google/uuid"
)

type Admin struct {
	ID       uuid.UUID
	Username string
	Passwd   string
}

type Catalog struct {
	ID          uuid.UUID
	Name        string
	Description string
	Price       int32
}
